site_name: Anton – Dokumentation
repo_url: https://github.com/kraenzle-ritter/anton-documentation
repo_name: 'anton-documentation'
site_author: 'Andreas Kraenzle, Gerold Ritter'
theme:
  name: material
  language: de
  logo: images/kr_logo.png
  favicon: images/favicon-anton.png
  font:
    text: Roboto
    code: Open Mono
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.inlinehilite
  - footnotes
  - toc:
      permalink: true
nav:
  - Home: index.md
  - User:
    - Einleitung: user/index.md
    - Signaturen: user/identifiers.md
    - Access-Konzept: user/access.md
    - Datenimport: user/import.md
    - Formulare: user/forms.md
    - Einstellungen: user/settings.md
    - File Uploads: user/uploads.md
    - Antonevents: user/antonevents.md
    - Entäten:
      - Akteure: user/actors.md
      - Orte: user/places.md
      - Schlagwörter: user/keywords.md
    - Externe Ressourcen: user/resources.md
  - Developer:
    - Forms: developer/forms.md
    - Fields: developer/fields.md
    - Data Tables: developer/data-tables.md
    - Search: developer/search.md
    - AntonObjects Sideeffects of Methods: developer/antonobjects-sideeffects.md
  - Admin:
    - Requirements: admin/requirements.md
    - Installation: admin/installation.md
    - Configuration: admin/configuration.md
    - Word Export: admin/word-export.md
    - Watermarks: admin/watermarks.md
    - Restore from Backup: admin/restore.md
    - Commands: admin/console-commands.md
    - Testinstallation k & r: admin/testarchive.md
  - API: api/index.md
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AndreasKraenzle
    - icon: fontawesome/brands/github
      link: https://github.com/kraenzle-ritter
plugins:
  - render_swagger
