site_name: Anton – Dokumentation
repo_url: https://github.com/kraenzle-ritter/anton-documentation
repo_name: 'anton-documentation'
site_author: 'Andreas Kraenzle, Gerold Ritter'
theme:
  name: material
  language: de
  logo: images/kr_logo.png
  favicon: images/favicon-anton.png
  font:
    text: Roboto
    code: Open Mono
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - admonition
  - codehilite
  - pymdownx.inlinehilite
  - pymdownx.inlinehilite
  - footnotes
  - attr_list
  - md_in_html
  - toc:
      permalink: true
nav:
  - Home: index.md
  - User:
    #- Einleitung: user/index.md
    - Signaturen: user/identifiers.md
    - Access-Konzept: user/access.md
    - Datenimport: user/import.md
    # - Formulare: user/forms.md
    # - Einstellungen: user/settings.md
    # - File Uploads: user/uploads.md
    # - Antonevents: user/antonevents.md
    #- Entitäten:
    #  - Akteure: user/actors.md
    #  - Orte: user/places.md
    #  - Schlagwörter: user/keywords.md
    # - Externe Ressourcen: user/resources.md
  #- Developer:
  #  - Forms: developer/forms.md
  #  - Fields: developer/fields.md
  #  - Data Tables: developer/data-tables.md
  #  - Search: developer/search.md
  #  - AntonObjects Sideeffects of Methods: developer/antonobjects-sideeffects.md
  - Admin:
    - Requirements: admin/requirements.md
    - Installation: admin/installation.md
    - Configuration: admin/configuration.md
    - Word Export: admin/word-export.md
    - Watermarks: admin/watermarks.md
    - Mastodon: admin/mastodon.md
    - Restore from Backup: admin/restore.md
    - Commands: admin/console-commands.md
    - Testinstallation k & r: admin/testarchive.md
  - API: api/index.md
  - FAQ:
    - Anton as Service: faq/anton_as_service.md
    - Anton on Premises: faq/anton_on_premises.md
    - Allgemeine FAQs: faq/index.md
    - Erschliessung: faq/erschliessung.md
    - Migration/Import: faq/import.md
    - Recherche und Benutzung: faq/recherche.md
    - Export: faq/export.md
extra:
  social:
    - icon: fontawesome/brands/mastodon
      link: https://social.anoxinon.de/@anton
    - icon: fontawesome/brands/github
      link: https://github.com/kraenzle-ritter
plugins:
  - render_swagger
